export enum ConsultStatus {
  CREATED = "CREATED",
  RECORDING_STARTED = "RECORDING_STARTED",
  RECORDING_FINISHED = "RECORDING_FINISHED",
  PROCESSING_COMPLETED = "PROCESSING_COMPLETED",
}

export enum RecordingStatus {
  TRANSCRIBE_STARTED = "TRANSCRIBE_STARTED",
  TRANSCRIBE_FINISHED = "TRANSCRIBE_FINISHED",
}
